#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import sys

def solve(n):
    a, b = 1, 1
    ans = 0
    for i in range(n-1):
        temp = a + b
        if(temp > n):
            break
        a = b
        b = temp
        if temp %2 == 0:
            ans += temp
        else:
            continue
    return ans

t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    print(solve(n))
